# Generated by Django 5.0.2 on 2024-03-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_description',
            new_name='receipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='reciepe_image',
            new_name='receipe_image',
        ),
    ]
